name: HubAPI
author: BebeDlaStreat
version: 0.1
description: A simpla API for mangage an hub/lobby
main: fr.bebedlastreat.hubapi.HubMain
commands:
  hub:
    aliases:
      - lobby
      - spawn
    description: Teleport to the hub